version: '3'

networks:
    staternetwork:
        driver: bridge

services:

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=myapp
            - MYSQL_ROOT_PASSWORD=123456
        networks: 
            - staternetwork
        ports:
            - "3307:3306"

    starterapp:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: starterapp
        environment: 
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=myapp
            - DB_USERNAME=root
            - DB_PASSWORD=123456
        entrypoint: ./dockerize -template ./application.properties:application.properties -wait tcp://db:3306 -timeout 60s ./starterapp.entrypoint.sh
        networks:
            - staternetwork
        depends_on:
            - db
    
    nginx:
        build:
            context: ./.docker/nginx
            dockerfile: Dockerfile
        container_name: nginx
        networks:
            - staternetwork
        ports:
            - "8080:80"